### ISSUE TITLE
Span tag usage

### ISSUE THREAD

**Issue by jim-rosales** [violetf/prj-rev-bwfs-dasmoto#3]
It was a good idea to use a div to add the bold blue style to your prices, but unfortunately a `<p>` tag cannot have a `<div>` tag inside of it. You can check out this [StackOverflow](https://stackoverflow.com/questions/8397852/why-p-tag-cant-contain-div-tag-inside-it) answer that explains the reason for this more in depth. 

Considering you can't use a div the best alternative is to use a span for example:
```HTML
 <span class="price">Starting at $5.00 / tube.</div></p>
```

If you use this approach then you don't need to update anything in your CSS file since the class is still being applied to the span.

Another alternative is to do the following and make use of the strong tag which makes text bold

```HTML
<strong>Starting at $5.00 / tube.</strong></p>
```

Then since the text is already being bolded by the strong tag you just need to update its color with some CSS
```CSS
strong {
  color: blue;
}
```

Either approach is acceptable and you achieve the same end result it's up to you to choose the one you feel best works with your project structure.

https://github.com/violetf/prj-rev-bwfs-dasmoto/blob/3e25385aa7e41e6a6ef6263c2e1dd7b1e59046f6/Dasmoto's_Arts_and_Crafts/index.html#L36

**Comment by violetf** [comment]
This helped by putting the prices inline with the rest of the <p> tag.  I was having a lot of trouble with that so thanks!
